In [2]:
import numpy as np

In [48]:
import math

$$|0) := \begin{bmatrix} 1 \\ 0 \end{bmatrix}$$

In [3]:
ket0 = np.array(
    [[1.+0.j,
      0.+0.j]])

$$|1) := \begin{bmatrix} 0 \\ 1 \end{bmatrix}$$

In [4]:
ket1 = np.array(
    [0.+0.j,
     1.+0.j])

$$ X(\alpha|0) + \beta|1)) :=
    \begin{bmatrix}
        0 & 1 \\
        1 & 0
    \end{bmatrix}
    (\alpha|0) + \beta|1))
  = \begin{bmatrix}
        0 & 1 \\
        1 & 0
    \end{bmatrix}
    \begin{bmatrix}
        \alpha \\
        \beta
    \end{bmatrix}
  = \begin{bmatrix}
        \beta \\
        \alpha
    \end{bmatrix}
$$

In [55]:
def X(mat: np.ndarray) -> np.ndarray:
    """Not gate. Inverts the state"""
    return mat.dot(np.array(
        [[0.+0.j, 1.+0.j],
         [1.+0.j, 0.+0.j]]))

$$
    H|0) = \frac{|0) + |1)}{\sqrt{2}} \\
    H|1) = \frac{|0) - |1)}{\sqrt{2}} \\
    H(\alpha|0) + \beta|1))
  = \alpha(\frac{|0) + |1)}{\sqrt{2}})
  + \beta(\frac{|0) - |1)}{\sqrt{2}}) \\
  = \frac{\alpha + \beta}{\sqrt{2}}|0)
  + \frac{\alpha - \beta}{\sqrt{2}}|1) \\
H = \frac{1}{\sqrt{2}}
    \begin{bmatrix}
        1 & 1 \\
        1 & -1
    \end{bmatrix}
$$

In [64]:
def H(mat: np.array) -> np.array:
    """Hadamard Gate"""
    return 1/np.sqrt(2) * mat.dot(np.array(
        [[1.+0.j, 1.+0.j],
         [1.+0.j, -1.+0.j]]))

$$ Y(\alpha + \beta) :=
    \begin{bmatrix}
        0 & -i \\
        i & 0
    \end{bmatrix}
    \begin{bmatrix}
        \alpha \\
        \beta
    \end{bmatrix}
  = \begin{bmatrix}
        i\beta \\
        -i\alpha
    \end{bmatrix}
$$

In [70]:
def Y(mat: np.array) -> np.array:
    """Pauli's Y matrix gate"""
    return mat.dot(np.array(
    [[0.+0.j, 0.+-1.j],
     [0.+1.j, 0.+0.j]]))

$$ Z(\alpha + \beta) :=
    \begin{bmatrix}
        1 & 0 \\
        0 & -1
    \end{bmatrix}
    \begin{bmatrix}
        \alpha \\
        \beta
    \end{bmatrix}
  = \begin{bmatrix}
        \alpha \\
        -\beta
    \end{bmatrix}
$$

In [71]:
def Z(mat: np.array) -> np.array:
    """Pauli's Z matrix gate"""
    return mat.dot(np.array(
        [[1.+0.j, 0.+0.j],
         [0.+0.j, -1.+0.j]]))

$$ R(\alpha + \beta) :=
    \begin{bmatrix}
        \cos{\theta} & -\sin{\theta} \\
        \sin{\theta} & \cos{\theta}
    \end{bmatrix}
    \begin{bmatrix}
        \alpha \\
        \beta
    \end{bmatrix}
$$

In [74]:
def R(mat: np.array, theta: float) -> np.array:
    c, s = np.cos(theta), np.sin(theta)
    return mat.dot(np.array(
        [[c, -s],
         [s, c]]))

$$ c :=
    \begin{bmatrix}
        0.6 \\
        0.8
    \end{bmatrix}
 =  \begin{bmatrix}
        \alpha \\
        \beta
    \end{bmatrix}
$$

In [5]:
c = np.array(
    [0.6+0.j,
     0.8+0.j])

$$  0.6|0) + 0.8|1)
  = 0.6 \begin{bmatrix} 1 \\ 0 \end{bmatrix}
  + 0.8 \begin{bmatrix} 0 \\ 1 \end{bmatrix}
  = \begin{bmatrix} 0.6 \\ 0.8 \end{bmatrix}
$$

In [7]:
c * ket0 + c * ket1

array([[0.6+0.j, 0.8+0.j]])

$$ c2 :=
    \frac{1+i}{2}|0)
  + \frac{i}{\sqrt{2}}|1)
  = \begin{bmatrix}
      \frac{1+i}{2} \\
      \frac{i}{\sqrt{2}}
    \end{bmatrix}
$$

In [8]:
c2 = np.array(
    [(1.+1.j) / 2,
     (0.+1.j) / np.sqrt(2.)])

In [9]:
c2 * ket0

array([[0.5+0.5j, 0. +0.j ]])

In [10]:
c2 * ket1

array([0.+0.j        , 0.+0.70710678j])

$$
    \begin{bmatrix}
        0 & 1 \\
        1 & 0
    \end{bmatrix}
    \begin{bmatrix}
        \frac{1+i}{2} \\
        \frac{i}{\sqrt{2}}
    \end{bmatrix}
  = \begin{bmatrix}
        0.707...j \\
        0.5+0.5j
    \end{bmatrix}
$$

In [21]:
X(c2)

array([0. +0.70710678j, 0.5+0.5j       ])

In [22]:
X(c)

array([0.8+0.j, 0.6+0.j])

In [54]:
def check_normalisation_constraint(mat: np.ndarray) -> bool:
    """The sum of the squares of the amplitudes of the superposition must be equal to 1"""
    return math.isclose(1, np.sum(np.abs(np.power(mat, 2))))

In [53]:
check_normalisation_constraint(c2)

True

In [51]:
check_normalisation_constraint(c)

True

In [65]:
H(c2)

array([0.35355339+0.85355339j, 0.35355339-0.14644661j])

In [67]:
np.sum(np.abs(np.power(H(c2), 2)))

0.9999999999999997

In [69]:
check_normalisation_constraint(X(H(c2)))

True

In [76]:
rc2 = R(c2, 90)

In [77]:
check_normalisation_constraint(rc2)

True